//! Poseidon hash over the odd scalar field `F_p` (secq scalar field) —
//! the N1 nullifier primitive (production fix for the P0 malleability).
//!
//! The consensus nullifier becomes `nf = Poseidon(x)` where `x = nk+rho`
//! is the value the S2b ownership path already binds via `C*`. It is a
//! **field element**, fully determined by the circuit witness, revealed
//! and constrained `circuit_nf == public_nf` — so there is no group
//! element, no blinding, and no free component (the P0 class is
//! structurally impossible), and no cross-cycle transport. `nf` depends
//! only on the *pinned sum* `x`, NOT on `(nk, rho)` individually — if it
//! depended on the split, a prover could re-split `x` into a different
//! `(nk, rho)` and mint a second nullifier for one note. See
//! `dev-docs/sidechain/n1-nullifier-fix-design.md` §0/§0b.
//!
//! One permutation drives BOTH the native oracle ([`hash1`]) and the
//! in-circuit gadget ([`hash1_gadget`]), so they agree by construction.
//! Round constants + MDS are generated by the standard Grain-LFSR
//! generator (`ark_crypto_primitives`) for this exact field; the
//! `(t, R_F, R_P, alpha)` choice + parameter set is the one bounded
//! external-review item (round counts vs algebraic attacks).

use std::sync::OnceLock;

use ark_crypto_primitives::sponge::poseidon::find_poseidon_ark_and_mds;
use ark_ff::PrimeField;
use curve_trees_bulletproofs::r1cs::{constant, ConstraintSystem, LinearCombination};

/// Odd scalar field (secq256k1 `Fr`) — the odd constraint system's
/// native field, and the field `x = nk+rho` lives in.
pub type Fp = ark_secq256k1::Fr;

/// Permutation width (rate 2 + capacity 1).
pub const T: usize = 3;
/// Sponge rate.
pub const RATE: usize = 2;
/// Full rounds (R_F, split R_F/2 before and after the partial rounds).
pub const R_F: usize = 8;
/// Partial rounds (R_P) — conservative for a 256-bit field, alpha=5;
/// the exact count is the parameter-review item.
pub const R_P: usize = 56;
/// S-box exponent (x^5; gcd(5, p-1)=1 verified, so it is a permutation).
pub const ALPHA: u64 = 5;
/// Domain-separation constant placed in the capacity/second slot.
pub const DOMAIN: u64 = 0x6165_6769_733a_6e66; // "aegis:nf" bytes, as a tag

struct Params {
    ark: Vec<Vec<Fp>>,
    mds: Vec<Vec<Fp>>,
}

fn params() -> &'static Params {
    static P: OnceLock<Params> = OnceLock::new();
    P.get_or_init(|| {
        let (ark, mds) = find_poseidon_ark_and_mds::<Fp>(
            Fp::MODULUS_BIT_SIZE as u64,
            RATE,
            R_F as u64,
            R_P as u64,
            0,
        );
        Params { ark, mds }
    })
}

fn is_full_round(r: usize) -> bool {
    !(R_F / 2..R_F / 2 + R_P).contains(&r)
}

fn sbox(x: Fp) -> Fp {
    let x2 = x * x;
    let x4 = x2 * x2;
    x4 * x
}

/// Native Poseidon permutation on a width-`T` state (matches the gadget).
fn permute(state: &mut [Fp; T]) {
    let p = params();
    for r in 0..(R_F + R_P) {
        for (i, s) in state.iter_mut().enumerate() {
            *s += p.ark[r][i];
        }
        if is_full_round(r) {
            for s in state.iter_mut() {
                *s = sbox(*s);
            }
        } else {
            state[0] = sbox(state[0]);
        }
        let mut next = [Fp::from(0u64); T];
        for (i, ni) in next.iter_mut().enumerate() {
            for (j, sj) in state.iter().enumerate() {
                *ni += p.mds[i][j] * sj;
            }
        }
        *state = next;
    }
}

/// Native fixed-length hash of one field element: `nf = Poseidon(x)`.
pub fn hash1(x: Fp) -> Fp {
    let mut state = [x, Fp::from(DOMAIN), Fp::from(0u64)];
    permute(&mut state);
    state[0]
}

// ---------- in-circuit gadget (mirrors the native permutation) ----------

fn sbox_gadget<CS: ConstraintSystem<Fp>>(
    cs: &mut CS,
    l: LinearCombination<Fp>,
) -> LinearCombination<Fp> {
    let (_, _, l2) = cs.multiply(l.clone(), l.clone());
    let (_, _, l4) = cs.multiply(l2.into(), l2.into());
    let (_, _, l5) = cs.multiply(l4.into(), l);
    l5.into()
}

fn permute_gadget<CS: ConstraintSystem<Fp>>(
    cs: &mut CS,
    mut state: [LinearCombination<Fp>; T],
) -> [LinearCombination<Fp>; T] {
    let p = params();
    for r in 0..(R_F + R_P) {
        for (i, s) in state.iter_mut().enumerate() {
            *s = s.clone() + constant(p.ark[r][i]);
        }
        if is_full_round(r) {
            for s in state.iter_mut() {
                *s = sbox_gadget(cs, s.clone());
            }
        } else {
            state[0] = sbox_gadget(cs, state[0].clone());
        }
        let mut next: [LinearCombination<Fp>; T] =
            std::array::from_fn(|_| LinearCombination::<Fp>::default());
        for (i, ni) in next.iter_mut().enumerate() {
            let mut acc = LinearCombination::<Fp>::default();
            for (j, sj) in state.iter().enumerate() {
                acc = acc + sj.clone().scalar_mul(p.mds[i][j]);
            }
            // Collapse each lane to a fresh variable (`acc·1 = v`) so the
            // non-S-boxed partial-round lanes cannot accumulate terms
            // exponentially (the recurrence a←1+2a over R_P rounds). Keeps
            // every LC bounded at ~T terms; values are unchanged.
            let (_, _, v) = cs.multiply(acc, constant(Fp::from(1u64)));
            *ni = v.into();
        }
        state = next;
    }
    state
}

/// In-circuit `nf = Poseidon(x)`: returns the LC the caller constrains
/// equal to the public nullifier.
pub fn hash1_gadget<CS: ConstraintSystem<Fp>>(
    cs: &mut CS,
    x: LinearCombination<Fp>,
) -> LinearCombination<Fp> {
    let state = [x, constant(Fp::from(DOMAIN)), constant(Fp::from(0u64))];
    let out = permute_gadget(cs, state);
    let [first, _, _] = out;
    first
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generators::OddPoint;
    use crate::tree::tree_params;
    use ark_ff::BigInteger;
    use curve_trees_bulletproofs::r1cs::{Prover, Verifier};
    use merlin::Transcript;

    // ----- happy path -----

    #[test]
    fn hash1_is_deterministic() {
        let x = Fp::from(12345u64);
        assert_eq!(hash1(x), hash1(x));
    }

    #[test]
    fn hash1_differs_per_input() {
        assert_ne!(hash1(Fp::from(1u64)), hash1(Fp::from(2u64)));
    }

    #[test]
    fn params_are_pinned() {
        // Golden regression: the generated round-constant/MDS set is
        // fixed (a change is chain-id-breaking). Pin a digest of the
        // hash of a fixed input, which depends on every param.
        let nf = hash1(Fp::from(0x1234_5678u64));
        let bytes = nf.into_bigint().to_bytes_be();
        assert_eq!(
            hex::encode(bytes),
            PINNED_HASH_HEX,
            "poseidon params or permutation drifted (chain-id-breaking)"
        );
    }

    /// Captured from this parameter set — see `params_are_pinned`.
    const PINNED_HASH_HEX: &str =
        "c9f655848ce3a386a277a838bc48257cf6fa75cd323086ccd12dc5fa42da6329";

    // ----- oracle parity / gadget soundness -----

    #[test]
    fn gadget_matches_native_and_binds_the_output() {
        // The decisive test: an in-circuit Poseidon(x) proof verifies iff
        // the revealed nf equals the native hash — changing nf to ANY
        // other value fails (no free component to absorb the change).
        let x = Fp::from(999u64);
        let nf = hash1(x);
        let pc = &tree_params().odd_parameters.pc_gens;
        let bp = &tree_params().odd_parameters.bp_gens;

        let proof = {
            let mut prover: Prover<_, OddPoint> =
                Prover::new(pc, Transcript::new(b"aegis:poseidon:test"));
            let (_c, x_var) = prover.commit(x, Fp::from(7u64));
            let out = hash1_gadget(&mut prover, x_var.into());
            prover.constrain(out - constant(nf));
            (prover.prove(bp).unwrap(), _c)
        };
        let (proof, x_comm) = proof;

        // Correct nf verifies.
        {
            let mut v: Verifier<_, OddPoint> =
                Verifier::new(Transcript::new(b"aegis:poseidon:test"));
            let x_var = v.commit(x_comm);
            let out = hash1_gadget(&mut v, x_var.into());
            v.constrain(out - constant(nf));
            assert!(v.verify(&proof, pc, bp).is_ok(), "honest nf must verify");
        }
        // Any other nf is rejected — this is the anti-malleability guarantee.
        {
            let mut v: Verifier<_, OddPoint> =
                Verifier::new(Transcript::new(b"aegis:poseidon:test"));
            let x_var = v.commit(x_comm);
            let out = hash1_gadget(&mut v, x_var.into());
            v.constrain(out - constant(nf + Fp::from(1u64)));
            assert!(v.verify(&proof, pc, bp).is_err(), "tampered nf must reject");
        }
    }
}
